// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: persistence/v1/service.proto

package persistencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PersistenceService_CreateSystem_FullMethodName         = "/persistence.v1.PersistenceService/CreateSystem"
	PersistenceService_GetSystems_FullMethodName           = "/persistence.v1.PersistenceService/GetSystems"
	PersistenceService_UpdateSystem_FullMethodName         = "/persistence.v1.PersistenceService/UpdateSystem"
	PersistenceService_DeleteSystem_FullMethodName         = "/persistence.v1.PersistenceService/DeleteSystem"
	PersistenceService_AddUser_FullMethodName              = "/persistence.v1.PersistenceService/AddUser"
	PersistenceService_GetUsers_FullMethodName             = "/persistence.v1.PersistenceService/GetUsers"
	PersistenceService_UpdateUser_FullMethodName           = "/persistence.v1.PersistenceService/UpdateUser"
	PersistenceService_DeleteUser_FullMethodName           = "/persistence.v1.PersistenceService/DeleteUser"
	PersistenceService_GetContacts_FullMethodName          = "/persistence.v1.PersistenceService/GetContacts"
	PersistenceService_Notify_FullMethodName               = "/persistence.v1.PersistenceService/Notify"
	PersistenceService_CreateScenario_FullMethodName       = "/persistence.v1.PersistenceService/CreateScenario"
	PersistenceService_GetScenarios_FullMethodName         = "/persistence.v1.PersistenceService/GetScenarios"
	PersistenceService_UpdateScenario_FullMethodName       = "/persistence.v1.PersistenceService/UpdateScenario"
	PersistenceService_DeleteScenario_FullMethodName       = "/persistence.v1.PersistenceService/DeleteScenario"
	PersistenceService_UpsertSubscriptions_FullMethodName  = "/persistence.v1.PersistenceService/UpsertSubscriptions"
	PersistenceService_GetSubscriptions_FullMethodName     = "/persistence.v1.PersistenceService/GetSubscriptions"
	PersistenceService_UpdateQuietHours_FullMethodName     = "/persistence.v1.PersistenceService/UpdateQuietHours"
	PersistenceService_UpdateDeliveryStatus_FullMethodName = "/persistence.v1.PersistenceService/UpdateDeliveryStatus"
)

// PersistenceServiceClient is the client API for PersistenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersistenceServiceClient interface {
	CreateSystem(ctx context.Context, in *CreateSystemRequest, opts ...grpc.CallOption) (*System, error)
	GetSystems(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*Systems, error)
	UpdateSystem(ctx context.Context, in *UpdateSystemRequest, opts ...grpc.CallOption) (*System, error)
	DeleteSystem(ctx context.Context, in *DeleteSystemRequest, opts ...grpc.CallOption) (*InfoMessage, error)
	// Users CRUD
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*Users, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*InfoMessage, error)
	// Returns contacts (email, phone, telegram) for users by their id_at_system within a system
	GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*UserContactsList, error)
	// Notifications
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// Scenarios CRUD
	CreateScenario(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*Scenario, error)
	GetScenarios(ctx context.Context, in *GetScenariosRequest, opts ...grpc.CallOption) (*ScenarioList, error)
	UpdateScenario(ctx context.Context, in *UpdateScenarioRequest, opts ...grpc.CallOption) (*Scenario, error)
	DeleteScenario(ctx context.Context, in *DeleteScenarioRequest, opts ...grpc.CallOption) (*InfoMessage, error)
	// Subscriptions & Preferences
	UpsertSubscriptions(ctx context.Context, in *UpsertSubscriptionsRequest, opts ...grpc.CallOption) (*UpsertSubscriptionsResponse, error)
	GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*GetSubscriptionsResponse, error)
	UpdateQuietHours(ctx context.Context, in *UpdateQuietHoursRequest, opts ...grpc.CallOption) (*InfoMessage, error)
	// Delivery status callback — called by orchestrator when adapter reports delivery result
	UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*InfoMessage, error)
}

type persistenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersistenceServiceClient(cc grpc.ClientConnInterface) PersistenceServiceClient {
	return &persistenceServiceClient{cc}
}

func (c *persistenceServiceClient) CreateSystem(ctx context.Context, in *CreateSystemRequest, opts ...grpc.CallOption) (*System, error) {
	out := new(System)
	err := c.cc.Invoke(ctx, PersistenceService_CreateSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) GetSystems(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (*Systems, error) {
	out := new(Systems)
	err := c.cc.Invoke(ctx, PersistenceService_GetSystems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) UpdateSystem(ctx context.Context, in *UpdateSystemRequest, opts ...grpc.CallOption) (*System, error) {
	out := new(System)
	err := c.cc.Invoke(ctx, PersistenceService_UpdateSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) DeleteSystem(ctx context.Context, in *DeleteSystemRequest, opts ...grpc.CallOption) (*InfoMessage, error) {
	out := new(InfoMessage)
	err := c.cc.Invoke(ctx, PersistenceService_DeleteSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, PersistenceService_AddUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, PersistenceService_GetUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, PersistenceService_UpdateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*InfoMessage, error) {
	out := new(InfoMessage)
	err := c.cc.Invoke(ctx, PersistenceService_DeleteUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*UserContactsList, error) {
	out := new(UserContactsList)
	err := c.cc.Invoke(ctx, PersistenceService_GetContacts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, PersistenceService_Notify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) CreateScenario(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*Scenario, error) {
	out := new(Scenario)
	err := c.cc.Invoke(ctx, PersistenceService_CreateScenario_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) GetScenarios(ctx context.Context, in *GetScenariosRequest, opts ...grpc.CallOption) (*ScenarioList, error) {
	out := new(ScenarioList)
	err := c.cc.Invoke(ctx, PersistenceService_GetScenarios_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) UpdateScenario(ctx context.Context, in *UpdateScenarioRequest, opts ...grpc.CallOption) (*Scenario, error) {
	out := new(Scenario)
	err := c.cc.Invoke(ctx, PersistenceService_UpdateScenario_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) DeleteScenario(ctx context.Context, in *DeleteScenarioRequest, opts ...grpc.CallOption) (*InfoMessage, error) {
	out := new(InfoMessage)
	err := c.cc.Invoke(ctx, PersistenceService_DeleteScenario_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) UpsertSubscriptions(ctx context.Context, in *UpsertSubscriptionsRequest, opts ...grpc.CallOption) (*UpsertSubscriptionsResponse, error) {
	out := new(UpsertSubscriptionsResponse)
	err := c.cc.Invoke(ctx, PersistenceService_UpsertSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) GetSubscriptions(ctx context.Context, in *GetSubscriptionsRequest, opts ...grpc.CallOption) (*GetSubscriptionsResponse, error) {
	out := new(GetSubscriptionsResponse)
	err := c.cc.Invoke(ctx, PersistenceService_GetSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) UpdateQuietHours(ctx context.Context, in *UpdateQuietHoursRequest, opts ...grpc.CallOption) (*InfoMessage, error) {
	out := new(InfoMessage)
	err := c.cc.Invoke(ctx, PersistenceService_UpdateQuietHours_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistenceServiceClient) UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*InfoMessage, error) {
	out := new(InfoMessage)
	err := c.cc.Invoke(ctx, PersistenceService_UpdateDeliveryStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistenceServiceServer is the server API for PersistenceService service.
// All implementations must embed UnimplementedPersistenceServiceServer
// for forward compatibility
type PersistenceServiceServer interface {
	CreateSystem(context.Context, *CreateSystemRequest) (*System, error)
	GetSystems(context.Context, *GetSystemsRequest) (*Systems, error)
	UpdateSystem(context.Context, *UpdateSystemRequest) (*System, error)
	DeleteSystem(context.Context, *DeleteSystemRequest) (*InfoMessage, error)
	// Users CRUD
	AddUser(context.Context, *AddUserRequest) (*User, error)
	GetUsers(context.Context, *GetUsersRequest) (*Users, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*InfoMessage, error)
	// Returns contacts (email, phone, telegram) for users by their id_at_system within a system
	GetContacts(context.Context, *GetContactsRequest) (*UserContactsList, error)
	// Notifications
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// Scenarios CRUD
	CreateScenario(context.Context, *CreateScenarioRequest) (*Scenario, error)
	GetScenarios(context.Context, *GetScenariosRequest) (*ScenarioList, error)
	UpdateScenario(context.Context, *UpdateScenarioRequest) (*Scenario, error)
	DeleteScenario(context.Context, *DeleteScenarioRequest) (*InfoMessage, error)
	// Subscriptions & Preferences
	UpsertSubscriptions(context.Context, *UpsertSubscriptionsRequest) (*UpsertSubscriptionsResponse, error)
	GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*GetSubscriptionsResponse, error)
	UpdateQuietHours(context.Context, *UpdateQuietHoursRequest) (*InfoMessage, error)
	// Delivery status callback — called by orchestrator when adapter reports delivery result
	UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*InfoMessage, error)
	mustEmbedUnimplementedPersistenceServiceServer()
}

// UnimplementedPersistenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPersistenceServiceServer struct {
}

func (UnimplementedPersistenceServiceServer) CreateSystem(context.Context, *CreateSystemRequest) (*System, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSystem not implemented")
}
func (UnimplementedPersistenceServiceServer) GetSystems(context.Context, *GetSystemsRequest) (*Systems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystems not implemented")
}
func (UnimplementedPersistenceServiceServer) UpdateSystem(context.Context, *UpdateSystemRequest) (*System, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSystem not implemented")
}
func (UnimplementedPersistenceServiceServer) DeleteSystem(context.Context, *DeleteSystemRequest) (*InfoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSystem not implemented")
}
func (UnimplementedPersistenceServiceServer) AddUser(context.Context, *AddUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedPersistenceServiceServer) GetUsers(context.Context, *GetUsersRequest) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedPersistenceServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedPersistenceServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*InfoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedPersistenceServiceServer) GetContacts(context.Context, *GetContactsRequest) (*UserContactsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContacts not implemented")
}
func (UnimplementedPersistenceServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedPersistenceServiceServer) CreateScenario(context.Context, *CreateScenarioRequest) (*Scenario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScenario not implemented")
}
func (UnimplementedPersistenceServiceServer) GetScenarios(context.Context, *GetScenariosRequest) (*ScenarioList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScenarios not implemented")
}
func (UnimplementedPersistenceServiceServer) UpdateScenario(context.Context, *UpdateScenarioRequest) (*Scenario, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScenario not implemented")
}
func (UnimplementedPersistenceServiceServer) DeleteScenario(context.Context, *DeleteScenarioRequest) (*InfoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteScenario not implemented")
}
func (UnimplementedPersistenceServiceServer) UpsertSubscriptions(context.Context, *UpsertSubscriptionsRequest) (*UpsertSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSubscriptions not implemented")
}
func (UnimplementedPersistenceServiceServer) GetSubscriptions(context.Context, *GetSubscriptionsRequest) (*GetSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedPersistenceServiceServer) UpdateQuietHours(context.Context, *UpdateQuietHoursRequest) (*InfoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuietHours not implemented")
}
func (UnimplementedPersistenceServiceServer) UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*InfoMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeliveryStatus not implemented")
}
func (UnimplementedPersistenceServiceServer) mustEmbedUnimplementedPersistenceServiceServer() {}

// UnsafePersistenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersistenceServiceServer will
// result in compilation errors.
type UnsafePersistenceServiceServer interface {
	mustEmbedUnimplementedPersistenceServiceServer()
}

func RegisterPersistenceServiceServer(s grpc.ServiceRegistrar, srv PersistenceServiceServer) {
	s.RegisterService(&PersistenceService_ServiceDesc, srv)
}

func _PersistenceService_CreateSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).CreateSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_CreateSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).CreateSystem(ctx, req.(*CreateSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_GetSystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetSystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetSystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetSystems(ctx, req.(*GetSystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_UpdateSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).UpdateSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_UpdateSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).UpdateSystem(ctx, req.(*UpdateSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_DeleteSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).DeleteSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_DeleteSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).DeleteSystem(ctx, req.(*DeleteSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetContacts(ctx, req.(*GetContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_CreateScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).CreateScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_CreateScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).CreateScenario(ctx, req.(*CreateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_GetScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetScenarios(ctx, req.(*GetScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_UpdateScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).UpdateScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_UpdateScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).UpdateScenario(ctx, req.(*UpdateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_DeleteScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).DeleteScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_DeleteScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).DeleteScenario(ctx, req.(*DeleteScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_UpsertSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).UpsertSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_UpsertSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).UpsertSubscriptions(ctx, req.(*UpsertSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_GetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).GetSubscriptions(ctx, req.(*GetSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_UpdateQuietHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuietHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).UpdateQuietHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_UpdateQuietHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).UpdateQuietHours(ctx, req.(*UpdateQuietHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersistenceService_UpdateDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistenceServiceServer).UpdateDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersistenceService_UpdateDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistenceServiceServer).UpdateDeliveryStatus(ctx, req.(*UpdateDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersistenceService_ServiceDesc is the grpc.ServiceDesc for PersistenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersistenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "persistence.v1.PersistenceService",
	HandlerType: (*PersistenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSystem",
			Handler:    _PersistenceService_CreateSystem_Handler,
		},
		{
			MethodName: "GetSystems",
			Handler:    _PersistenceService_GetSystems_Handler,
		},
		{
			MethodName: "UpdateSystem",
			Handler:    _PersistenceService_UpdateSystem_Handler,
		},
		{
			MethodName: "DeleteSystem",
			Handler:    _PersistenceService_DeleteSystem_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _PersistenceService_AddUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _PersistenceService_GetUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _PersistenceService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _PersistenceService_DeleteUser_Handler,
		},
		{
			MethodName: "GetContacts",
			Handler:    _PersistenceService_GetContacts_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _PersistenceService_Notify_Handler,
		},
		{
			MethodName: "CreateScenario",
			Handler:    _PersistenceService_CreateScenario_Handler,
		},
		{
			MethodName: "GetScenarios",
			Handler:    _PersistenceService_GetScenarios_Handler,
		},
		{
			MethodName: "UpdateScenario",
			Handler:    _PersistenceService_UpdateScenario_Handler,
		},
		{
			MethodName: "DeleteScenario",
			Handler:    _PersistenceService_DeleteScenario_Handler,
		},
		{
			MethodName: "UpsertSubscriptions",
			Handler:    _PersistenceService_UpsertSubscriptions_Handler,
		},
		{
			MethodName: "GetSubscriptions",
			Handler:    _PersistenceService_GetSubscriptions_Handler,
		},
		{
			MethodName: "UpdateQuietHours",
			Handler:    _PersistenceService_UpdateQuietHours_Handler,
		},
		{
			MethodName: "UpdateDeliveryStatus",
			Handler:    _PersistenceService_UpdateDeliveryStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persistence/v1/service.proto",
}
