title: &title orchestrator

settings:
  contract_version: "1.0.0"
  operations_topics:
    send_notification_orchestration: send-notification-orchestrator
    delivery_email: delivery-email
    delivery_telegram: delivery-telegram
    delivery_sms: delivery-sms
    delivery_status: delivery-status

  action_execution_timeout: "30s"

server:
    http:
        address: ":8081"

integrations:
  rpc:
    persistence:
      address: "persistence-service:9090"

connections:
  kafka:
    gateway:
      brokers:
        - "kafka:29092"
      consumer_group: "orchestrator-consumer-group"
      consumer_workers_count: 10
      retry:
        net_timeout: 3s
        dial_timeout: 5s
        max_retries: 3
        initial_backoff: 1s
        max_backoff: 60s
        backoff_multiplier: 2
        max_reconnect_tries: 0
      health_check_timeout: 30s
      auth:
        enable_auth: false
        mechanism: "SCRAM-SHA-512"
        username: "KAFKA_USERNAME"
        password: "KAFKA_PASSWORD_ENC"
        certificate: "KAFKA_CA_ENC"

telemetry:
  # add telemetry config later
